services:

  mysql:
    image: mysql
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: home_energy_tracker
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-data:/var/log/mysql

  kafka:
    container_name: kafka
    image: apache/kafka:latest
    ports:
      - "9092:9092"
      - "9094:9094"

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CLUSTER_ID: 'energy-tracker-1'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      KAFKA_LISTENERS: >
        PLAINTEXT://0.0.0.0:9092,
        EXTERNAL://0.0.0.0:9094,
        CONTROLLER://0.0.0.0:9093

      KAFKA_ADVERTISED_LISTENERS: >
        PLAINTEXT://kafka:9092,
        EXTERNAL://localhost:9094

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >
        CONTROLLER:PLAINTEXT,
        PLAINTEXT:PLAINTEXT,
        EXTERNAL:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    volumes:
      - kafka_data:/var/lib/kafka/data

  kafka-ui:
    container_name: kafka-ui
    image: kafbat/kafka-ui:latest
    ports:
      - "8070:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    restart: unless-stopped

  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3-core
    user: root
    ports:
      - 8181:8181
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
      - --admin-token-file=/docker/influxdb/admin-token.json
    volumes:
      - influxdb_data:/var/lib/influxdb3/data
      - influxdb_data:/var/lib/influxdb3/plugins
      - ./docker/influxdb/admin-token.json:/docker/influxdb/admin-token.json:ro

  influxdb3-init:
    container_name: influxdb3-init
    image: influxdb:3-core
    user: root
    depends_on:
      - influxdb3-core
    volumes:
      - ./docker/influxdb/admin-token.json:/docker/influxdb/admin-token.json:ro
      - ./docker/influxdb/init.sh:/init.sh:ro
    entrypoint: ["/bin/sh", "/init.sh"]
    restart: "no"

  influxdb3-explorer:
    container_name: influxdb3-explorer
    image: influxdata/influxdb3-ui
    ports:
      - "8080:8080"
      - "8443:8443"
    command:
      - --mode=admin
    depends_on:
      - influxdb3-core
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.7.1
    ports:
      - "8091:8080"
    command:
      - start-dev
      - --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./docker/keycloak:/opt/keycloak/data/import:ro

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./docker/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    restart: always

volumes:
  db-data:
  kafka_data:
  influxdb_data:
  keycloak_data:
  