services:

  mysql:
    image: mysql
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: home_energy_tracker
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - db-data:/var/logs/mysql


volumes:
  db-data: