spring.application.name=insight-service
server.port=8086

# spring ai
spring.ai.google.genai.api-key=AIzaSyDNOaW_tP_vEnZmtb31_QA1QaA_nrbcZpI
spring.ai.google.genai.chat.model=gemini-3.5-flash

# clients
usage.service.base.url=http://localhost:8084/api/v1/usage
#OpenAPI
openapi.server.url=http://localhost:9000
openapi.security.authorization-url=http://localhost:8091/realms/home-energy-tracker/protocol/openid-connect/auth
openapi.security.token-url=http://localhost:8091/realms/home-energy-tracker/protocol/openid-connect/token

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

#Swagger OAuth2
springdoc.swagger-ui.oauth.client-id=home-energy-tracker-browser
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.scopes=openid
