spring.application.name=usage-service
server.port=8084

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=usage-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.meichel.kafka_event

# Kafka provider
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer

# influxdb
influxdb.token=apiv3_HFHds6UumitlYNdSphHCaCu0NA4S_oaBhzHY6i6HESW-DQjB1OBja-NX4leGrTvym8UQDjCW27I9b-lozw1KzQ
influxdb.host=http://localhost:8181
influxdb.database=energy-tracker

# Device service
device.service.base.url=http://localhost:8082

#User service
user.service.base.url=http://localhost:8081


#OpenAPI
openapi.server.url=http://localhost:9000
openapi.security.authorization-url=http://localhost:8091/realms/home-energy-tracker/protocol/openid-connect/auth
openapi.security.token-url=http://localhost:8091/realms/home-energy-tracker/protocol/openid-connect/token

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}

#Swagger OAuth2
springdoc.swagger-ui.oauth.client-id=home-energy-tracker-browser
springdoc.swagger-ui.oauth.use-pkce-with-authorization-code-grant=true
springdoc.swagger-ui.oauth.scopes=openid
