spring.application.name=device-service
server.port=8082

# jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# mysql
spring.datasource.url=jdbc:mysql://localhost:3306/home_energy_tracker
spring.datasource.username=root
spring.datasource.password=password

logging.level.org.flywaydb=DEBUG

#OpenAPI
springdoc.swagger-ui.enabled=false
openapi.server.url=http://localhost:9000
openapi.security.authorization-url=http://localhost:8091/realms/home-energy-tracker/protocol/openid-connect/auth
openapi.security.token-url=http://localhost:8091/realms/home-energy-tracker/protocol/openid-connect/token

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
